### PR TITLE
added dataSource name to the datasources metadata

### PR DESCRIPTION
**Pull request by reggev**
This change is [Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)

### CODE REVIEW

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @NassiHarel and @reggev)

___
*[lib/dataSource-parser.js, line 13 at r1](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLDouKV21KhgYsJCUpN:-MLDouKV21KhgYsJCUpO:brglpvj) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/36f1b64373de6079739e2eb3f841813a2aed000f/lib/dataSource-parser.js#L13)):*
> ```JavaScript
>         });
>     }
> ```

What I meant is:
```
   const results = parser.extractDataSourceMetaData({ pipeline, storagePrefix });
   const { metadata, dataSources } = results;
   metadata = map as today
   dataSources = array with distinct names
```

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[lib/dataSource-parser.js, line 10 at r1](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLDpOKE75slo3UjUBbI:-MLDpOKFELYAWZcQwn0K:b4uaf5c) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/36f1b64373de6079739e2eb3f841813a2aed000f/lib/dataSource-parser.js#L10)):*
> ```
>  return { storageInfo: { path: `${storagePrefix}/${dataSourceName}/${pattern}`, dataSourceName } };
> ```

It shouldn't be part of storageInfo

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @NassiHarel)

___
*[lib/dataSource-parser.js, line 10 at r1](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLDpOKE75slo3UjUBbI:-MLE9D8P0kyRcRd4SlhP:b-896fix) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/36f1b64373de6079739e2eb3f841813a2aed000f/lib/dataSource-parser.js#L10)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
>  return { storageInfo: { path: `${storagePrefix}/${dataSourceName}/${pattern}`, dataSourceName } };
> ```

It shouldn't be part of storageInfo
</blockquote></details>

Done.
___
*[lib/dataSource-parser.js, line 13 at r1](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLDouKV21KhgYsJCUpN:-MLE9DSP0UMTwFJEKW0H:b-896fix) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/36f1b64373de6079739e2eb3f841813a2aed000f/lib/dataSource-parser.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

What I meant is:
```
   const results = parser.extractDataSourceMetaData({ pipeline, storagePrefix });
   const { metadata, dataSources } = results;
   metadata = map as today
   dataSources = array with distinct names
```
  
</blockquote></details>

Done.

**Review by NassiHarel — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @NassiHarel and @reggev)

___
*[lib/dataSource-parser.js, line 13 at r2](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLGy244AIKzSgnDMPyn:-MLGy244AIKzSgnDMPyo:b63h50z) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/e1790d85716e5510202b0e6ff937938dcdc66021/lib/dataSource-parser.js#L13)):*
> ```
> extractDataSourceMetaData({ pipeline, storagePrefix }) {
> ```

Why not keep it simple:
```
        const dsKeys = new Set();
        const metadata = helpers.pipelineNodesToMetaData(pipeline, (v => helpers.isDataSource(v)), (path) => {
            const { pattern, dataSourceName } = this._parseEntry(path);
            dsKeys.add(dataSourceName);
            return { storageInfo: { path: `${storagePrefix}/${dataSourceName}/${pattern}` } };
        });
        const dataSources = [...dsKeys];
        return { metadata, dataSources };

```

**Review by reggev — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @NassiHarel)

___
*[lib/dataSource-parser.js, line 13 at r2](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-MLGy244AIKzSgnDMPyn:-MLH8NIiBXfcvGyRh1n9:bjplb20) ([raw file](https://github.com/kube-hpc/parsers.hkube/blob/e1790d85716e5510202b0e6ff937938dcdc66021/lib/dataSource-parser.js#L13)):*
<details><summary><i>Previously, NassiHarel (Nassi Harel) wrote…</i></summary><blockquote>

> ```
> extractDataSourceMetaData({ pipeline, storagePrefix }) {
> ```

Why not keep it simple:
```
        const dsKeys = new Set();
        const metadata = helpers.pipelineNodesToMetaData(pipeline, (v => helpers.isDataSource(v)), (path) => {
            const { pattern, dataSourceName } = this._parseEntry(path);
            dsKeys.add(dataSourceName);
            return { storageInfo: { path: `${storagePrefix}/${dataSourceName}/${pattern}` } };
        });
        const dataSources = [...dsKeys];
        return { metadata, dataSources };

```

</blockquote></details>

I think both solutions are not ideal, the actual issues is helpers.pipelineNodesToMetaData, but since it is such a minor issue and the side effect is constrained I'll take your suggestion.

**Review by NassiHarel — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/kube-hpc/parsers.hkube/13#-:-MLHO0W21DwvdGbXFprj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
